inveniosoftware/invenio-collections

CHANGES.rst, RELEASE-NOTES.rst, invenio_collections/cache.py, invenio_collections/collections_2015_07_14_innodb.py, invenio_collections/decorators.py, invenio_collections/forms.py, invenio_collections/models.py, invenio_collections/recordext/functions/get_record_collections.py, invenio_collections/version.py, invenio_collections/views/admin.py, invenio_collections/views/collections.py, requirements-devel.txt, setup.py
=> Invenio-Collections v0.1.0

AUTHORS.rst, CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_collections/translations/de/LC_MESSAGES/messages.po, invenio_collections/translations/es/LC_MESSAGES/messages.po, invenio_collections/translations/fr/LC_MESSAGES/messages.po, invenio_collections/translations/invenio.pot, invenio_collections/translations/it/LC_MESSAGES/messages.po, invenio_collections/version.py, setup.cfg
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> Invenio-Collections v0.1.1

invenio_collections/cache.py
* NEW Ports get_permitted_restricted_collections function from
`invenio_search` package.
=> cache: get_permitted_restricted_collections port

invenio_collections/models.py
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> models: removal of unused import

invenio_collections/version.py
=> version: post-release version bump

.travis.invenio.cfg, .travis.yml, CHANGES.rst, RELEASE-NOTES.rst, invenio_collections/version.py
=> Invenio-Collections v0.2.0

invenio_collections/contrib/dojson.py, invenio_collections/tests/test_contrib_dojson.py, setup.py
Depends on https://github.com/inveniosoftware/dojson/pull/33
=> dojson: entry points usage

CHANGES.rst, RELEASE-NOTES.rst, invenio_collections/version.py
=> Invenio-Collections v0.3.0

.gitignore, invenio_collections/cli.py, invenio_collections/errors.py, invenio_collections/ext.py, invenio_collections/models.py, setup.py, tests/conftest.py, tests/test_cli.py, tests/test_invenio_collections.py
=> cli: initial implementation

invenio_collections/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> version: post-release bump

.editorconfig, .travis.yml, MANIFEST.in, invenio_collections/config.py, invenio_collections/ext.py, invenio_collections/models.py, invenio_collections/percolator.py, invenio_collections/receivers.py, invenio_collections/views.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/data/records/authorities/authority-v1.0.0.json, tests/data/records/record-v1.0.0.json, tests/test_invenio_collections.py, tests/test_percolator.py, tests/test_receivers.py, tests/test_record_signals.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> global: elasticsearch percolator

CHANGES.rst, RELEASE-NOTES.rst, invenio_collections/version.py
ping @JavierDelgadoFernandez - https://github.com/cernanalysispreservation/analysis-preservation.cern.ch/pull/73
=> release: v1.0.0a2

setup.py, tests/conftest.py
* Removes obsolete configuration.
(see inveniosoftware/invenio-search@cc05a96)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: SEARCH_AUTOINDEX removal

docs/conf.py, invenio_collections/config.py, invenio_collections/views.py, setup.py
* Allows configuration of template to be rendered by default for
collection landing pages.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> config: default view configuration

CHANGES.rst, RELEASE-NOTES.rst, invenio_collections/version.py, run-tests.sh
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> release: v1.0.0a3

docs/api.rst, docs/conf.py, invenio_collections/cli.py, invenio_collections/config.py, invenio_collections/ext.py, invenio_collections/models.py, invenio_collections/percolator.py, invenio_collections/query.py, invenio_collections/receivers.py
* Improves method documentation. (addresses #59)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> docs: addition of method documentation

.tx/config, invenio_collections/translations/cs/LC_MESSAGES/messages.po, invenio_collections/translations/da/LC_MESSAGES/messages.po, invenio_collections/translations/de/LC_MESSAGES/messages.po, invenio_collections/translations/fr/LC_MESSAGES/messages.po, invenio_collections/translations/it/LC_MESSAGES/messages.po, invenio_collections/translations/messages.pot
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
=> i18n: tx configuration fix

invenio_collections/ext.py, setup.py, tests/test_invenio_collections.py
=> ext: better handling of state and cli

.lgtm, MAINTAINERS, MANIFEST.in, invenio_collections/config.py, invenio_collections/ext.py, tests/test_receivers.py
Signed-off-by: Jiri Kuncar jiri.kuncar@cern.ch
=> docs: MAINTAINERS file and LGTM configuration

.travis.yml, invenio_collections/alembic/97faa437d867_create_collections_tables.py, invenio_collections/alembic/ce7adcbe1c6c_create_collections_branch.py, setup.py, tests/conftest.py, tests/test_invenio_collections.py, tests/test_percolator.py
=> global: initial alembic recipes
